name = "utopia-blog"
compatibility_date = "2026-03-28"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "utopia-db"
database_id = "__FILL_AFTER_CREATION__"

# R2 Bucket
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "utopia-images"

[vars]
NEXT_PUBLIC_IMAGE_URL = "/.pic/"
