// Matches the warm-paper palette in the author's Typora selfuse.css.
// Diagrams and code remain light even when the page's night mode is enabled.
export const readingPalette = {
    paper: "#faf8f4",
    ink: "#35312b",
    muted: "#766c60",
    border: "#b6a895",
    line: "#85786a",
    sand: "#eee5d8",
    sage: "#e3eadf",
    blue: "#e2e9ed",
    rose: "#f1e2da",
    code: "#f5f1e9",
}

const p = readingPalette
const diagramColors = [
    p.sand, p.sage, p.blue, p.rose,
    "#e9e2ed", "#f2ead9", "#dce8e4", "#e8e6dc",
    "#ecdcd5", "#dce4ec", "#e6ebd9", "#e9dfd2",
]

export const mermaidThemeVariables = {
    darkMode: false,
    background: p.paper,
    fontFamily: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
    fontSize: "14px",
    primaryColor: p.sand,
    secondaryColor: p.sage,
    tertiaryColor: p.blue,
    primaryTextColor: p.ink,
    secondaryTextColor: p.ink,
    tertiaryTextColor: p.ink,
    primaryBorderColor: p.border,
    secondaryBorderColor: p.border,
    tertiaryBorderColor: p.border,
    textColor: p.ink,
    lineColor: p.line,
    edgeLabelBackground: p.paper,
    clusterBkg: "#f2eee6",
    clusterBorder: p.border,
    noteBkgColor: "#f2ead9",
    noteBorderColor: p.border,
    noteTextColor: p.ink,
    actorBkg: p.sand,
    actorBorder: p.border,
    actorTextColor: p.ink,
    actorLineColor: p.line,
    signalColor: p.line,
    signalTextColor: p.ink,
    activationBkgColor: p.sage,
    activationBorderColor: p.border,
    sequenceNumberColor: p.paper,
    sectionBkgColor: "#f2eee6",
    sectionBkgColor2: p.paper,
    altSectionBkgColor: p.paper,
    taskBkgColor: p.blue,
    taskBorderColor: p.border,
    activeTaskBkgColor: p.sage,
    activeTaskBorderColor: p.border,
    doneTaskBkgColor: "#ebe7df",
    doneTaskBorderColor: p.border,
    critBkgColor: p.rose,
    critBorderColor: "#ae7964",
    taskTextColor: p.ink,
    taskTextLightColor: p.ink,
    taskTextDarkColor: p.ink,
    taskTextOutsideColor: p.ink,
    todayLineColor: "#a65f40",
    gridColor: "#ded5c8",
    labelBackgroundColor: p.paper,
    compositeBackground: p.paper,
    compositeTitleBackground: p.sand,
    pieStrokeColor: p.paper,
    pieStrokeWidth: "2px",
    pieOuterStrokeColor: p.border,
    pieOuterStrokeWidth: "1px",
    pieOpacity: "1",
    pieSectionTextColor: p.ink,
    pieLegendTextColor: p.ink,
    pieTitleTextColor: p.ink,
    commitLabelColor: p.ink,
    commitLabelBackground: p.paper,
    tagLabelColor: p.ink,
    tagLabelBackground: p.sand,
    tagLabelBorder: p.border,
    ...Object.fromEntries(diagramColors.flatMap((color, i) => [
        [`pie${i + 1}`, color],
        [`cScale${i}`, color],
        [`cScaleLabel${i}`, p.ink],
        ...(i < 8 ? [[`git${i}`, color], [`gitBranchLabel${i}`, p.ink]] : []),
    ])),
}

const codeBase = {
    color: p.ink,
    background: "transparent",
    fontFamily: 'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
    fontSize: "0.875rem",
    lineHeight: "1.6",
    textShadow: "none",
}

export const warmCodeTheme = {
    'code[class*="language-"]': codeBase,
    'pre[class*="language-"]': codeBase,
    comment: { color: "#7b7164" },
    prolog: { color: "#7b7164" },
    doctype: { color: "#7b7164" },
    cdata: { color: "#7b7164" },
    punctuation: { color: p.muted },
    keyword: { color: "#97583e" },
    operator: { color: "#97583e" },
    string: { color: "#526a4b" },
    char: { color: "#526a4b" },
    "attr-value": { color: "#526a4b" },
    number: { color: "#806047" },
    boolean: { color: "#806047" },
    constant: { color: "#806047" },
    function: { color: "#4d6878" },
    property: { color: "#4d6878" },
    "class-name": { color: "#4d6878" },
    tag: { color: "#79617b" },
    builtin: { color: "#79617b" },
    "attr-name": { color: "#6e653e" },
    regex: { color: "#6e653e" },
    important: { color: "#97583e", fontWeight: "bold" },
    bold: { fontWeight: "bold" },
    italic: { fontStyle: "italic" },
    deleted: { color: "#a34737" },
    inserted: { color: "#526a4b" },
}
